/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bblfsh_client_libuast_Libuast */

#ifndef _Included_org_bblfsh_client_libuast_Libuast
#define _Included_org_bblfsh_client_libuast_Libuast
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bblfsh_client_libuast_Libuast
 * Method:    filter
 * Signature: (ILjava/lang/String;)Lscala/collection/immutable/List;
 */
// XXX jobject return
JNIEXPORT jint JNICALL Java_org_bblfsh_client_libuast_Libuast_filter
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
