/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bblfsh_client_v2_libuast_Libuast_TreeOrder__ */

#ifndef _Included_org_bblfsh_client_v2_libuast_Libuast_TreeOrder__
#define _Included_org_bblfsh_client_v2_libuast_Libuast_TreeOrder__
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
