/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bblfsh_client_v2_ContextExt */

#ifndef _Included_org_bblfsh_client_v2_ContextExt
#define _Included_org_bblfsh_client_v2_ContextExt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bblfsh_client_v2_ContextExt
 * Method:    root
 * Signature: ()Lorg/bblfsh/client/v2/NodeExt;
 */
JNIEXPORT jobject JNICALL Java_org_bblfsh_client_v2_ContextExt_root
  (JNIEnv *, jobject);

/*
 * Class:     org_bblfsh_client_v2_ContextExt
 * Method:    filter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bblfsh_client_v2_ContextExt_filter
  (JNIEnv *, jobject);

/*
 * Class:     org_bblfsh_client_v2_ContextExt
 * Method:    encode
 * Signature: (Lorg/bblfsh/client/v2/NodeExt;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_bblfsh_client_v2_ContextExt_encode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_bblfsh_client_v2_ContextExt
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bblfsh_client_v2_ContextExt_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
