/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bblfsh_client_v2_libuast_Libuast_UastIterExt */

#ifndef _Included_org_bblfsh_client_v2_libuast_Libuast_UastIterExt
#define _Included_org_bblfsh_client_v2_libuast_Libuast_UastIterExt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bblfsh_client_v2_libuast_Libuast_UastIterExt
 * Method:    nativeNext
 * Signature: (J)Lorg/bblfsh/client/v2/NodeExt;
 */
JNIEXPORT jobject JNICALL Java_org_bblfsh_client_v2_libuast_Libuast_00024UastIterExt_nativeNext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_bblfsh_client_v2_libuast_Libuast_UastIterExt
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bblfsh_client_v2_libuast_Libuast_00024UastIterExt_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     org_bblfsh_client_v2_libuast_Libuast_UastIterExt
 * Method:    nativeDispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bblfsh_client_v2_libuast_Libuast_00024UastIterExt_nativeDispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
