/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bblfsh_client_v2_Node */

#ifndef _Included_org_bblfsh_client_v2_Node
#define _Included_org_bblfsh_client_v2_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bblfsh_client_v2_Node
 * Method:    load
 * Signature: ()Lorg/bblfsh/client/v2/JNode;
 */
JNIEXPORT jobject JNICALL Java_org_bblfsh_client_v2_Node_load
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
