/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bblfsh_client_v2_NodeExt */

#ifndef _Included_org_bblfsh_client_v2_NodeExt
#define _Included_org_bblfsh_client_v2_NodeExt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bblfsh_client_v2_NodeExt
 * Method:    load
 * Signature: ()Lorg/bblfsh/client/v2/JNode;
 */
JNIEXPORT jobject JNICALL Java_org_bblfsh_client_v2_NodeExt_load
  (JNIEnv *, jobject);

/*
 * Class:     org_bblfsh_client_v2_NodeExt
 * Method:    filter
 * Signature: (Ljava/lang/String;)Lorg/bblfsh/client/v2/libuast/Libuast/UastIterExt;
 */
JNIEXPORT jobject JNICALL Java_org_bblfsh_client_v2_NodeExt_filter
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
