/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bblfsh_client_v2_Context__ */

#ifndef _Included_org_bblfsh_client_v2_Context__
#define _Included_org_bblfsh_client_v2_Context__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bblfsh_client_v2_Context__
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_bblfsh_client_v2_Context_00024_create
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
