/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bblfsh_client_v2_libuast_Libuast */

#ifndef _Included_org_bblfsh_client_v2_libuast_Libuast
#define _Included_org_bblfsh_client_v2_libuast_Libuast
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bblfsh_client_v2_libuast_Libuast
 * Method:    decode
 * Signature: (Ljava/nio/ByteBuffer;)Lorg/bblfsh/client/v2/Context;
 */
JNIEXPORT jobject JNICALL Java_org_bblfsh_client_v2_libuast_Libuast_decode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_bblfsh_client_v2_libuast_Libuast
 * Method:    filter
 * Signature: (Lorg/bblfsh/client/v2/Node;Ljava/lang/String;)Lscala/collection/immutable/List;
 */
JNIEXPORT jobject JNICALL Java_org_bblfsh_client_v2_libuast_Libuast_filter
  (JNIEnv *, jobject, jobject, jstring);

jint JNI_OnLoad(JavaVM *vm, void *reserved);

#ifdef __cplusplus
}
#endif
#endif
